language: php
php:
  - '7.0'

script:
  - composer global require "squizlabs/php_codesniffer=*"
  - composer global require "cakephp/cakephp-codesniffer"
  - ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/cakephp/cakephp-codesniffer
  - ~/.composer/vendor/bin/phpcs --config-set default_standard CakePHP
  - ~/.composer/vendor/bin/phpcbf ~/build/kubotan/phptest/src/
