language: php
php:
  - '7.0'

script:
  - composer global require "squizlabs/php_codesniffer=*"
  - composer global require "cakephp/cakephp-codesniffer"
  - cd ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/
  - ln -s ~/.composer/vendor/pear-pear.cakephp.org/CakePHP_CodeSniffer/PHP/CodeSniffer/Standards/CakePHP/ CakePHP
  - ~/.composer/vendor/bin/phpcs --standard=CakePHP 
  - ~/.composer/vendor/bin/phpcbf ./
