language: php
php:
  - '7.0'

script:
  - composer global require "squizlabs/php_codesniffer=*"
  - composer global require "cakephp/cakephp-codesniffer"
  - ~/.composer/vendor/bin/phpcs --standard=CakePHP 
  - ~/.composer/vendor/bin/phpcbf ./
